version: "3"

silent: true

vars:
  PACKAGE_SRC_DIR: asknews_sdk

tasks:
  # Unit tests
  test:
    cmds:
      - coverage run -m pytest --junitxml=report.xml {{.CLI_ARGS}}
      - coverage report
      - coverage xml
      - coverage html -d coverage-report

  # Lint
  lint:
    cmds:
      - |
        if [ -n "{{.SRC_DIR}}" ]; then
          export SRC_DIR="{{.SRC_DIR}}"
        else
          export SRC_DIR="{{.PACKAGE_SRC_DIR}}"
        fi
      - uvx ruff check $SRC_DIR {{.CLI_ARGS}}
      - |
        if [ "{{.FORMAT}}" = "true" ]; then
          uvx ruff format $SRC_DIR {{.CLI_ARGS}}
        fi

  # Build
  build:
    cmds:
      - uv build --wheel
