name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.12
    environment:
      name: pypi
      url: https://pypi.org/p/asknews/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "15"
        with:
          path: |
            ~/.cache/pip
          key: pip-${{ runner.os }}-${{ runner.arch }}-py-${{ matrix.python-version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Cache uv
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "15"
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ runner.arch }}-py-${{ matrix.python-version }}-uv-${{ hashFiles('uv.lock') }}
      - name: Install dependencies
        run: |
          uv sync --refresh
          uv cache prune --ci
          echo $VIRTUAL_ENV/bin >> $GITHUB_PATH
      - name: Install task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: task build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
